version: "3.8"
services:
  db:
    image: postgres
    container_name: Larry-Pgepita
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: larry
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: larryadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: lawrence-kaara.mburia@epita.fr
      PGADMIN_DEFAULT_PASSWORD: admin22
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

